### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by omarcartera** [shatrix/COVID19_Tracker_Android#11]
It just started to happen today, the log is attached below.

Phone: Poco F1
Android: 10

```
java.lang.NumberFormatException: For input string: "N/A"

at

sun.misc.FloatingDecimal.readJavaFormatString(FloatingD ecimal.java:2043) at

sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) va:110) at java.lang.Double.parseDouble(Double.java:538) at

com.shatrix.covid19tracker.MainActivity$7$1.run(MainActi vity.java:447) at android.os.Handler.handleCallback(Handler.java:883) at android.os.Handler.dispatchMessage(Handler.java:

100) at android.os.Looper.loop(Looper.java:224) at android.app.ActivityThread.main(ActivityThread.java:

7520) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.Runtimeinit$MethodAndArgsCaller .run(RuntimeInit.java:539) at

com.android.internal.os.Zygoteinit.main(Zygoteinit.java:

950)
```

**Comment by shatrix** [comment]
Fixed in V3.3
https://github.com/shatrix/COVID19_Tracker_Android/commit/6e5060f139f0d758545a113757f61b1bd5035806

Release uploaded
https://github.com/shatrix/COVID19_Tracker_Android/releases/tag/3.3
